INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1001, 'Arun', 'Learn Linux for Dev', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1002, 'Arun', 'Learn Cloud for Dev', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1003, 'Arun', 'Learn Network for Dev', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1004, 'Arun', 'Learn FullStack Development', CURRENT_DATE(), false);